#!/usr/bin/env python3
"""Export every data-bearing manuscript figure's numbers as pgfplots input.

The figures used to be matplotlib PDFs.  That had two costs.  The visible one
was typographic: the exports carried DejaVu Sans and Liberation Serif into a
document set in Times, which is what a reader registers as "these came from
somewhere else".  The invisible one was that a figure's numbers lived inside a
plotting call, so re-reading them meant re-reading plotting code.

Redrawing in pgfplots fixes the type.  This script keeps the other property
``make_paper_figures.py`` established -- every printed value is read from an
artifact in ``reports/`` or ``docs/``, nothing is hardcoded, and a
decomposition that fails to close raises instead of drawing.  The .tex figure
sources under ``docs/figure-sources/tikz/`` read what this writes and contain
no numbers of their own.

Two kinds of output:

``data/<fig>.dat``  whitespace tables, consumed by ``\\addplot table``.
``data/<fig>.tex``  scalar macros (``\\SG...``) for values that
                    appear in an axis annotation rather than as a coordinate.

Usage (fish):
    uv run python scripts/export_figure_data.py
    uv run python scripts/export_figure_data.py --check   # verify, write nothing
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "docs" / "figure-sources" / "tikz" / "data"


def _load(rel: str) -> dict:
    return json.loads((REPO / rel).read_text())


class Writer:
    """Collects output so ``--check`` can run every computation and write nothing."""

    def __init__(self, check: bool) -> None:
        self.check = check
        self.notes: list[str] = []

    def table(self, name: str, header: list[str], rows: list[list[object]]) -> None:
        if self.check:
            return
        w = "  ".join(header) + "\n"
        for r in rows:
            w += "  ".join(str(c) for c in r) + "\n"
        (OUT / f"{name}.dat").write_text(w)

    def macros(self, name: str, pairs: dict[str, str]) -> None:
        if self.check:
            return
        body = "% generated by scripts/export_figure_data.py -- do not edit\n"
        for k, v in pairs.items():
            body += f"\\newcommand{{\\{k}}}{{{v}}}\n"
        (OUT / f"{name}.tex").write_text(body)

    def say(self, s: str) -> None:
        self.notes.append(s)


# ---------------------------------------------------------------- fig_decomp
def decomp(w: Writer) -> None:
    """Oracle affine decomposition of the ETTm2 retrieval branch."""
    d = _load("reports/error-decomposition/ettm2-test-error-decomposition.json")["decomposition"]
    m, a = d["mse"], d["attribution"]

    raw_gap = m["raw_retrieval"] - m["shape_floor_oracle_rescaled"]
    removed = a["scale_error_removed_by_restoration"]
    remaining = a["scale_error_remaining"]
    # A waterfall that does not close is not a decomposition. This is the check
    # the pre-generator version of this figure had no way to fail.
    if abs(raw_gap - removed - remaining) > 1e-6:
        raise ValueError(f"waterfall does not close: {raw_gap} != {removed} + {remaining}")

    shape_pct = 100.0 * a["shape_fraction_of_restored_error"]
    floor_r = m["shape_floor_oracle_rescaled"]
    floor_b = m["shape_floor_backbone_oracle_rescaled"]

    # The second bar FLOATS -- it runs from what restoration leaves up to
    # where the raw analogue started -- and that is what makes the panel a
    # waterfall rather than four unrelated bars.  pgfplots has no per-point
    # base for ybar, so each bar is emitted as an explicit (bottom, top)
    # pair and drawn as a rectangle.
    bars = [
        (0.0, raw_gap),
        (raw_gap - removed, raw_gap),
        (0.0, remaining),
        (0.0, floor_r),
    ]
    w.macros(
        "decomp",
        {
            f"SGbar{chr(65 + i)}{k}": f"{v:.6f}"
            for i, (lo, hi) in enumerate(bars)
            for k, v in (("lo", lo), ("hi", hi))
        }
        | {
            "SGdecompRawGap": f"{raw_gap:.2f}",
            "SGdecompRemoved": f"{removed:.2f}",
            "SGdecompRemaining": f"{remaining:.3f}",
            "SGdecompFloor": f"{floor_r:.3f}",
            "SGdecompBackbone": f"{m['backbone']:.4f}",
            "SGdecompShapePct": f"{shape_pct:.1f}",
            "SGdecompMagPct": f"{100.0 - shape_pct:.1f}",
            "SGdecompFloorR": f"{floor_r:.4f}",
            "SGdecompFloorB": f"{floor_b:.4f}",
            "SGdecompWorsePct": f"{100.0 * (floor_r / floor_b - 1.0):.0f}",
            "SGdecompRealised": f"{a['restored_retrieval_vs_backbone_ratio']:.2f}",
            "SGdecompSymmetric": f"{1.0 / a['symmetric_shape_ratio']:.2f}",
        },
    )
    w.say(f"decomp: {raw_gap:.4f} = {removed:.4f} removed + {remaining:.4f} left, closes")
    w.say(f"decomp: shape {shape_pct:.1f}% / magnitude {100.0 - shape_pct:.1f}%")


# ------------------------------------------------------------------ fig3_band
def band(w: Writer) -> None:
    """Per-bin win rate and mean effect, branch and fused, across 50 origins."""
    import sys as _sys

    _sys.path.insert(0, str(REPO / "src"))
    from scalerag.sparse_regime import FIXED_BIN_EDGES, bin_index

    files = sorted(
        (REPO / "reports" / "sparse-scale-rule" / "ckpt").glob("s1000-seed42-origin*.npz")
    )
    if len(files) != 50:
        raise ValueError(f"expected 50 origin checkpoints, found {len(files)}")
    nb = FIXED_BIN_EDGES.size - 1
    acc: dict[str, list[list[float]]] = {
        k: [[] for _ in range(nb)] for k in ("bw", "fw", "bm", "fm")
    }
    for f in files:
        with np.load(f) as z:
            bb, br, fu = z["rmsse_backbone"], z["rmsse_mean"], z["rmsse_fused_mean"]
            ok = np.isfinite(bb) & np.isfinite(br) & np.isfinite(fu) & ~z["never_launched"]
            idx = bin_index(z["zero_fraction"])
            for b in range(nb):
                m = ok & (idx == b)
                if m.sum() < 5:
                    continue
                acc["bw"][b].append(float((bb[m] > br[m]).mean()))
                acc["fw"][b].append(float((bb[m] > fu[m]).mean()))
                acc["bm"][b].append(float((bb[m] - br[m]).mean()))
                acc["fm"][b].append(float((bb[m] - fu[m]).mean()))

    def agg(key: str) -> tuple[np.ndarray, np.ndarray]:
        mu = np.array([np.mean(acc[key][b]) for b in range(nb)])
        se = np.array([np.std(acc[key][b], ddof=1) / np.sqrt(len(acc[key][b])) for b in range(nb)])
        return mu, se

    mid = 0.5 * (FIXED_BIN_EDGES[:-1] + FIXED_BIN_EDGES[1:])
    bw, bwse = agg("bw")
    fw, fwse = agg("fw")
    bm, bmse = agg("bm")
    fm, fmse = agg("fm")
    ci = 1.96

    # The branch column must reproduce the recorded profile, or this is not the
    # estimator the paper already reports.
    ref = _load("reports/regime-threshold/m5-val-regime-threshold-1000-50origins.json")[
        "fixed_bin_profile_across_origins"
    ]
    for b, row in enumerate(ref):
        if abs(row["win_rate_mean"] - bw[b]) > 5e-3:
            raise ValueError(
                f"bin {b}: recomputed {bw[b]:.4f} vs recorded {row['win_rate_mean']:.4f}"
            )
    if not np.all(fw >= bw):
        raise ValueError("fusion is expected to raise the win rate in every bin")

    w.table(
        "band",
        ["z", "bwin", "bwinerr", "fwin", "fwinerr", "bmean", "bmeanerr", "fmean", "fmeanerr"],
        [
            [
                f"{mid[b]:.3f}",
                f"{bw[b]:.5f}",
                f"{ci * bwse[b]:.5f}",
                f"{fw[b]:.5f}",
                f"{ci * fwse[b]:.5f}",
                f"{bm[b]:.5f}",
                f"{ci * bmse[b]:.5f}",
                f"{fm[b]:.5f}",
                f"{ci * fmse[b]:.5f}",
            ]
            for b in range(nb)
        ],
    )
    sig = fm - ci * fmse > 0
    peak = int(np.argmax(bw))
    w.macros(
        "band",
        {
            "SGbandPeak": f"{bw[peak]:.2f}",
            "SGbandPeakZ": f"{mid[peak]:.2f}",
            "SGbandDense": f"{bw[0]:.2f}",
            "SGbandLo": f"{FIXED_BIN_EDGES[:-1][sig].min():.1f}",
            "SGbandHi": f"{FIXED_BIN_EDGES[1:][sig].max():.1f}",
            "SGbandSparseWin": f"{fw[-1]:.2f}",
            "SGbandSparseMean": f"{fm[-1]:.3f}",
        },
    )
    w.say(f"band: branch peak {bw[peak]:.3f} at z={mid[peak]:.2f}, dense {bw[0]:.3f}")
    w.say(
        f"band: fused mean clear of zero over "
        f"[{FIXED_BIN_EDGES[:-1][sig].min():.1f}, {FIXED_BIN_EDGES[1:][sig].max():.1f}]; "
        f"sparsest bin wins {fw[-1]:.3f} of the time on a mean of {fm[-1]:+.4f}"
    )


# ----------------------------------------------------------------- fig_pareto
def pareto(w: Writer) -> None:
    """Accuracy against latency on one device, with the CPU measurement kept visible.

    The latency axis is the thing referee item 19 was about: the original
    figure set a CPU-resident index against GPU-resident competitors. All
    three points here are one device, and the superseded CPU measurement is
    drawn hollow rather than deleted, because the honest claim is that the
    gap narrowed to 16% and not that it was never 131%.
    """
    bb = _load("reports/phase11a/compute_backbone.json")
    sr = _load("reports/phase11a/compute_scalerag.json")
    cost = _load("reports/ettm2-cost/ettm2-val-cost.json")
    ts = _load("reports/phase11a/repro_tsrag_official_ettm2.json")
    base = _load("reports/phase11a/repro_chronos_bolt_target_ettm2.json")
    native = _load("reports/phase11a/scalerag_native_ettm2_test.json")

    mse_bb, mse_ts = base["mse"], ts["mse"]
    mse_sr = next(
        r["mse"]
        for r in native["scalerag_restored_fixed_fusion"]
        if r["scale"] == "mean" and r["k"] == 20 and r["weight"] == 0.25
    )

    lat_bb = bb["backbone_latency_ms_per_window"]
    lat_cpu_idx = sr["retrieval_latency_ms_per_window"]
    speedup = cost["latency_ms_per_query"]["speedup"]
    if not cost["gpu_matches_cpu_exactly"]:
        raise ValueError("the GPU retriever is not bit-identical; the speedup is not transferable")
    lat_gpu_idx = lat_cpu_idx / speedup
    # TS-RAG's end-to-end latency is the backbone scaled by the measured
    # wall-clock ratio of the two reproduction runs, not an increment on it.
    lat_ts = lat_bb * (ts["eval_seconds"] / base["eval_seconds"])
    tot_cpu, tot_gpu = lat_bb + lat_cpu_idx, lat_bb + lat_gpu_idx

    # One row per system, so each can carry its own mark and its own label.
    # Encoding trainable parameters as marker area was tried and dropped: two
    # of the three systems train nothing, and an area scale that shows 0,
    # 3,000 and 4.78M on one page is not a scale. The counts are in the labels.
    w.table("paretoback", ["x", "y"], [[f"{lat_bb:.4f}", f"{mse_bb:.6f}"]])
    w.table("paretotsrag", ["x", "y"], [[f"{lat_ts:.4f}", f"{mse_ts:.6f}"]])
    w.table("paretoours", ["x", "y"], [[f"{tot_gpu:.4f}", f"{mse_sr:.6f}"]])
    w.table("paretocpu", ["x", "y"], [[f"{tot_cpu:.4f}", f"{mse_sr:.6f}"]])
    w.macros(
        "pareto",
        {
            "SGparetoBackMs": f"{lat_bb:.3f}",
            "SGparetoTsragMs": f"{lat_ts:.3f}",
            "SGparetoGpuMs": f"{tot_gpu:.3f}",
            "SGparetoCpuMs": f"{tot_cpu:.3f}",
            "SGparetoSpeedup": f"{speedup:.1f}",
            "SGparetoOverhead": f"{100.0 * (tot_gpu / lat_ts - 1.0):.0f}",
            "SGparetoTsragParams": f"{bb['arm_extra_params_trained'] / 1e6:.2f}",
            "SGparetoBackMse": f"{mse_bb:.5f}",
            "SGparetoTsragMse": f"{mse_ts:.5f}",
            "SGparetoOursMse": f"{mse_sr:.5f}",
        },
    )
    w.say(
        f"pareto: backbone {lat_bb:.3f} ms, TS-RAG {lat_ts:.3f} ms, "
        f"ScaleRAG {tot_cpu:.3f} CPU -> {tot_gpu:.3f} GPU ({speedup:.1f}x on the index)"
    )
    w.say(f"pareto: MSE {mse_bb:.5f} / {mse_ts:.5f} / {mse_sr:.5f}")
    w.say(f"pareto: still dominated, by {100.0 * (tot_gpu / lat_ts - 1.0):.0f}% of latency")


# ---------------------------------------------------------------- fig_metrics
METRICS = [("rmsse", "RMSSE"), ("wrmsse", "WRMSSE"), ("mase", "MASE"), ("wape", "WAPE")]
SYSTEMS = [
    ("seasonal_naive", "S-Naive"),
    ("lightgbm", "LightGBM"),
    ("chronos2_target", "Chronos-2"),
    ("ScaleRAG_gated", "ScaleRAG"),
]


def metrics(w: Writer) -> None:
    """The M5 held-out test panel: four metrics, four systems, and who leads each."""
    d = _load("docs/scalerag-heldout-test-tables.json")["test"]["methods"]
    winners = []
    for mi, (key, _) in enumerate(METRICS):
        vals = [d[s][key] for s, _ in SYSTEMS]
        best = int(np.argmin(vals))
        winners.append(SYSTEMS[best][1])
        # Systems are laid out top to bottom in SYSTEMS order, so the y
        # coordinate counts down from the top rather than up from the axis.
        # split rather than overlaid: an overlaid best-bar would print its
        # value twice, once from each series
        w.table(
            f"metric{mi}",
            ["y", "v"],
            [[len(SYSTEMS) - 1 - si, f"{v:.6f}"] for si, v in enumerate(vals) if si != best],
        )
        w.table(f"metric{mi}best", ["y", "v"], [[len(SYSTEMS) - 1 - best, f"{vals[best]:.6f}"]])
    # The figure's whole argument is that the ranking reorders, so assert it does.
    if len(set(winners)) == 1:
        raise ValueError(
            f"one system leads every metric ({winners[0]}); the figure claims otherwise"
        )
    w.macros(
        "metrics",
        {f"SGwinner{chr(65 + i)}": n for i, n in enumerate(winners)}
        | {f"SGlabel{chr(65 + i)}": lab for i, (_, lab) in enumerate(METRICS)}
        | {f"SGsys{chr(65 + i)}": lab for i, (_, lab) in enumerate(SYSTEMS)},
    )
    w.say(
        "metrics: leaders "
        + ", ".join(f"{m[1]}={n}" for m, n in zip(METRICS, winners, strict=True))
    )


# --------------------------------------------------------------- fig_ablation
def ablation(w: Writer) -> None:
    """Per-channel ETTm2 retrieval MSE, raw against restored, at the deployed k."""
    j = _load("reports/phase11a/scalerag_native_ettm2_test.json")
    names = j["variables"]
    z = np.load(REPO / "reports/phase11a/scalerag_native_ettm2_test_preds.npz")
    trues, var_of = z["trues"], z["var_of"]
    raw, res = z["raw_mean_20"], z["res_mean_20"]

    per, improved = [], 0
    for vi, nm in enumerate(names):
        m = var_of == vi
        r = float(np.mean((raw[m] - trues[m]) ** 2))
        s = float(np.mean((res[m] - trues[m]) ** 2))
        improved += int(s < r)
        per.append((nm, r, s))
    # worst raw error at the top, so the panel reads as a ranking
    per.sort(key=lambda t: t[1])
    rows = [[i, f"{r:.6f}", f"{s:.6f}"] for i, (_, r, s) in enumerate(per)]

    # Pooled MSE must reproduce the recorded k=20 entry, or these are not the
    # arrays the reported result was computed from.
    def rec(block: str) -> float:
        return next(e["mse"] for e in j[block] if e["scale"] == "mean" and e["k"] == 20)

    for got, want, lab in (
        (float(np.mean((raw - trues) ** 2)), rec("scalerag_raw_retrieval"), "raw"),
        (float(np.mean((res - trues) ** 2)), rec("scalerag_restored_retrieval"), "restored"),
    ):
        if abs(got - want) > 1e-4:
            raise ValueError(f"{lab} pooled MSE {got:.6f} disagrees with the recorded {want:.6f}")

    w.table("ablation", ["i", "raw", "restored"], rows)
    # dumbbell connectors: one two-point path per channel, blank-line separated,
    # read back under `empty line=jump'
    if not w.check:
        seg = "x  y\n" + "\n\n".join(
            f"{r:.6f}  {i}\n{s:.6f}  {i}" for i, (_, r, s) in enumerate(per)
        )
        (OUT / "ablationlink.dat").write_text(seg + "\n")
        # channel names, generated rather than retyped, so the labels cannot
        # drift out of step with the rows above
        (OUT / "ablationnames.tex").write_text(
            "% generated by scripts/export_figure_data.py -- do not edit\n"
            "\\pgfplotsset{ablnames/.style={ytick={"
            + ",".join(str(i) for i in range(len(per)))
            + "}, yticklabels={"
            + ",".join(nm for nm, _, _ in per)
            + "}}}\n"
        )

    # The M5 companion deliberately carries three marks, not two.  Raw
    # retrieval on M5 is only 2% off the deployed branch, so a two-point
    # raw-vs-restored panel would understate what restoration does; the
    # decisive contrast is the normalised-but-unrestored ablation, which is
    # 3.8x worse than either.  Panel (a) and panel (b) therefore contrast
    # different things and the figure has to say so.
    m5 = _load("docs/scalerag-final-tables.json")["m5_1000"]
    m5_raw = m5["methods_rmsse"]["retrieval_raw"]
    m5_norm = m5["key_ablations"]["norm_no_restore"]
    m5_res = m5["methods_rmsse"]["retrieval_scaleaware_P5"]
    w.table("ablationm5raw", ["x", "y"], [[f"{m5_raw:.6f}", 0]])
    w.table("ablationm5norm", ["x", "y"], [[f"{m5_norm:.6f}", 0]])
    w.table("ablationm5res", ["x", "y"], [[f"{m5_res:.6f}", 0]])
    w.macros(
        "ablation",
        {
            "SGablImproved": str(improved),
            "SGablTotal": str(len(names)),
            "SGablRawPooled": f"{rec('scalerag_raw_retrieval'):.3f}",
            "SGablResPooled": f"{rec('scalerag_restored_retrieval'):.3f}",
            "SGablFactor": f"{rec('scalerag_raw_retrieval') / rec('scalerag_restored_retrieval'):.1f}",
            "SGablMfiveRaw": f"{m5_raw:.3f}",
            "SGablMfiveNorm": f"{m5_norm:.3f}",
            "SGablMfiveRes": f"{m5_res:.3f}",
            "SGablMfiveFactor": f"{m5_norm / m5_res:.1f}",
        },
    )
    w.say(
        f"ablation: M5 val raw {m5_raw:.4f}, normalised-unrestored {m5_norm:.4f}, "
        f"restored {m5_res:.4f} ({m5_norm / m5_res:.1f}x)"
    )
    w.say(f"ablation: {improved}/{len(names)} ETTm2 channels improve under restoration")
    w.say(
        f"ablation: pooled {rec('scalerag_raw_retrieval'):.4f} raw -> "
        f"{rec('scalerag_restored_retrieval'):.4f} restored"
    )


# --------------------------------------------------------------- fig_mismatch
def mismatch(w: Writer) -> None:
    r"""One window: what the raw analogue mean looks like, and what restoring it does.

    The figure illustrates the failure mode Section I names "catastrophic
    scale mismatch": a retrieved analogue with the right shape at the wrong
    level, which restoration repairs. So the window is drawn from exactly
    that population -- OT windows where the raw analogue's shape correlation
    with the realised future is >= 0.8 AND restoration reduces the error --
    and within it, the one whose |log| raw-to-true RMS ratio is the median.
    Taking the median of the ratio itself would be the wrong centre, since
    ratios of 2 and 1/2 are the same size of error in opposite directions.

    Both halves of the criterion are needed, and both are exported so the
    caption can say how much of the channel they cover. Keying on RMS alone
    drew a window with shape correlation -0.79 under a caption saying the
    shape was right; keying on shape alone drew one where restoration made
    the error worse under a caption saying it repaired it.
    """
    import sys as _sys

    _sys.path.insert(0, str(REPO / "scripts"))
    import ettm2_data as ettm2

    j = _load("reports/phase11a/scalerag_native_ettm2_test.json")
    names = j["variables"]
    vi = names.index("OT")
    z = np.load(REPO / "reports/phase11a/scalerag_native_ettm2_test_preds.npz")
    trues, var_of, origins = z["trues"], z["var_of"], z["origins"]
    raw, res = z["raw_mean_20"], z["res_mean_20"]

    m = np.flatnonzero(var_of == vi)
    t_win, r_win = trues[m], raw[m]
    # shape agreement, scale-free: Pearson correlation per window
    tc = t_win - t_win.mean(1, keepdims=True)
    rc = r_win - r_win.mean(1, keepdims=True)
    denom = np.sqrt((tc**2).sum(1) * (rc**2).sum(1))
    shape = np.where(denom > 0, (tc * rc).sum(1) / np.maximum(denom, 1e-12), 0.0)
    shape_min = 0.8
    helped = ((res[m] - t_win) ** 2).mean(1) < ((r_win - t_win) ** 2).mean(1)
    good = (shape >= shape_min) & helped
    share_good = float(good.mean())
    share_helped = float(helped.mean())

    rms_t = np.sqrt(np.mean(t_win**2, axis=1))
    rms_r = np.sqrt(np.mean(r_win**2, axis=1))
    ratio = rms_r / np.maximum(rms_t, 1e-12)
    mism = np.abs(np.log(np.maximum(ratio, 1e-12)))  # size of the mismatch, either way
    cand = np.flatnonzero(good)
    order = cand[np.argsort(mism[cand])]
    sel = int(order[len(order) // 2])  # median mismatch among shape-matched windows
    pick = m[sel]
    if shape[sel] < shape_min:
        raise ValueError("selected window fails its own shape criterion")

    ctx_n = 120
    z_all, var_names = ettm2.load_normalized()
    if var_names[vi] != "OT":
        raise ValueError(f"channel order moved: expected OT at {vi}, found {var_names[vi]}")
    # ``origins`` is the global index of the first forecast step, so the
    # context ends at it and the horizon starts at it.
    o = int(origins[pick])
    ctx = z_all[o - ctx_n : o, vi]
    fut = z_all[o : o + ettm2.H, vi]
    if not np.allclose(fut, trues[pick], atol=1e-4):
        raise ValueError("reconstructed future does not match the stored target for this window")

    w.table("mismatchctx", ["t", "y"], [[t - ctx_n, f"{v:.5f}"] for t, v in enumerate(ctx)])
    w.table(
        "mismatch",
        ["t", "true", "raw", "restored"],
        [
            [t, f"{trues[pick][t]:.5f}", f"{raw[pick][t]:.5f}", f"{res[pick][t]:.5f}"]
            for t in range(ettm2.H)
        ],
    )
    w.macros(
        "mismatch",
        {
            "SGmisRatio": f"{ratio[sel]:.2f}",
            # the selection rule keys on RMS, but on this window the damage is
            # mostly LEVEL, which is the paper's finding, so report both
            "SGmisTrueLevel": f"{float(np.mean(trues[pick])):+.2f}",
            "SGmisRawLevel": f"{float(np.mean(raw[pick])):+.2f}",
            "SGmisResLevel": f"{float(np.mean(res[pick])):+.2f}",
            "SGmisPctWorse": f"{100.0 * float(np.mean(mism[cand] > mism[sel])):.0f}",
            "SGmisShape": f"{shape[sel]:.2f}",
            "SGmisShapeMin": f"{shape_min:.1f}",
            "SGmisShareGood": f"{100.0 * share_good:.0f}",
            "SGmisShareHelped": f"{100.0 * share_helped:.0f}",
            "SGmisRawMse": f"{np.mean((raw[pick] - trues[pick]) ** 2):.3f}",
            "SGmisResMse": f"{np.mean((res[pick] - trues[pick]) ** 2):.3f}",
            "SGmisCtx": str(ctx_n),
            # axis range from the data, padded, so a rule that picks a
            # different window cannot leave the drawing clipped
            "SGmisYmin": f"{min(ctx.min(), fut.min(), raw[pick].min(), res[pick].min()) - 0.35:.2f}",
            "SGmisYmax": f"{max(ctx.max(), fut.max(), raw[pick].max(), res[pick].max()) + 0.55:.2f}",
        },
    )
    w.say(
        f"mismatch: OT window at origin {o}, shape corr {shape[sel]:+.2f}, RMS ratio "
        f"{ratio[sel]:.3f}; median of the {100 * share_good:.0f}% of the channel with shape >= "
        f"{shape_min} where restoration helps (it helps on {100 * share_helped:.0f}%)"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="run every computation, write nothing")
    a = ap.parse_args()
    OUT.mkdir(parents=True, exist_ok=True)
    w = Writer(a.check)
    for fn in (decomp, band, pareto, metrics, ablation, mismatch):
        fn(w)
    print("\n".join(w.notes))
    print("checked, nothing written" if a.check else f"written to {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
